language: ruby

rvm:
  - 2.6

cache: bundler

# Imagemagick is required For favicon-maker
addons:
  - imagemagick

branches:
  only:
  - source

env:
  global:
    - GH_COMMIT_AUTHOR='Travis CI'
    - GH_COMMIT_EMAIL='travis@travis-ci.org'

script:
  - bundle exec rake travis:script

after_success:
  - bundle exec rake travis:after_success
