language: ruby

rvm:
  - 3.0.1
cache: bundler

addons:
  - imagemagick
services:
  - docker

branches:
  only:
    - source

env:
  global:
    - GH_COMMIT_AUTHOR='Travis CI'
    - GH_COMMIT_EMAIL='travis@travis-ci.org'
    - secure: AXWfr2601528bMqyxdyqdnQtdlNifK45XWRVv5dOq5nBB7BOPBdFwGduYxdhDKwGCHjeHhCw9jVnAUnwbrs+FJ89PQoEM17po7TNVa7Mrs+qF52Kas2GnAgVwmoAt7IujxjdVO5rqJeNz+Whmuuz/p1auxIw8ioz9dq8pSSYLAJWlH7UVYA/xrdVXDL8Bw6ZYuuLI78CmcXcNCk+FVxPvq5CjQoTWT14QxCNhl13YmxmIJUU41kQpS+Tth7nO8hNnyHr1M/pc48Ei/Zwsv6jyfZVBs89IbsFxyZX1ZG+E85KaojKWh8LBLYeIXtU3yA4JNn+XO6t7Fqg0T43GItBsKyI0ddBUKGG9zf5H0Emterqkxd3+kFGTSr1pVMg2eXdkwiNB9JizYNoiZOw3LGGqaNTVF6piMoqt5Kx/CzBpgVeTs5WUTi1Nxrw99rY9rfrCQp96T+Bl8jU+cAHDjZP/j+uUB5g9tpCbt54cwhrltuihzIT9tQ4rgPoZI2zyAKu8gVtyRP+heF5TRlK2mhuVCpc9R2oyVi+gerJaZOBYRlaKtQQ9+JOU7MXCqnoOyd117+3RjNWqqSqvB+XKHeAIZQea+UIM3xWZm1tN0CAHq+EymqYnK5D8CcwwnOmKsVL2Ac9lAVKQVu+C2O3JkfWEgr23gb4EalSzsNzIglbU8s=
    - secure: UztyofSYkrAbC3IViMxchIxaClLBy3TNmiyNGxUHgLSdH3ogQIQbZMazX+q/uiJBKy6YePtF8K7I7jg4f2KlhkC/9gkFTLdznBCELmnxxfwPZq0i4YH5ho0PJuxvSoon9XA20M4XfzE1lrZhfWJKVzQVZIIeLAAsKw+32HQU8aT1wcyO18r0sLqJI87oXkOKZiGvF5DjDqQjKNgWeQ2FlRNoq1lyNvXCD0IhaYuNJ8/CgA/7MX9wrDvDWqSmUi5Il2KhYP8Hbuhy4fKkHTLTFhVfoOA6j4ijDyB+alzQMkCusPq9gYTBDPo/FtHQIzRaZ/wBBTiEeteTQv8Woc22yBCq/uYYv1sYVRmTJcA+30tJHfPoBkjl5KYzPeH2PFvGScFllKSBeqWR6SZHQ4a82/LKl3T+cFAx+pFXlLz2CScpCYmfP4heKL+dtQxZui6GqkLU5cWkgtsnyCYsJuAqFFrMttrkp20hsB10+ekzRzFc1BBTTvyW32R/aWZJxO+PyPYJn9jkfLyClHc4TKk+pktVDyGA47aLzUgsW60e4uj/Sr8iohrGGrHHGSGy0vmu1bj6vfNRHPEeHzVMG1f0+PTAkufZRTRncJW5ZPur1gqWxjwkpIyXdEask9i8v41+0G3PBMo8GF2vSXICFmC2NB0rabY1XGDkuFFPwx0Lqf0=
script:
  - bundle exec rake travis:script
after_success:
  - bundle exec rake travis:after_success
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  - docker build . -f production.Dockerfile -t mayurifag/mayurifag.github.io:latest
  - docker push mayurifag/mayurifag.github.io:latest
