language: ruby

rvm:
- 2.6.1

cache: bundler

addons:
  apt:
    packages:
    - imagemagick

branches:
  only:
  - source

# Temporary Travis has to install latest 2.x bundler
before_install:
  - gem install bundler

script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'travis@travis-ci.org'
  - git remote set-url origin https://Mayurifag:${GH_TOKEN}@github.com/Mayurifag/mayurifag.github.io.git
  - bundle exec middleman deploy
