language: ruby

rvm:
  - 3.0.1
cache: bundler

addons:
  - imagemagick
services:
  - docker

branches:
  only:
    - source

env:
  global:
    - GH_COMMIT_AUTHOR='Travis CI'
    - GH_COMMIT_EMAIL='travis@travis-ci.org'
    - secure: "AjalUQpPphn8zw+M6IIq2X8K2HMOhYCoyp7I5UnCpG9JQe9pherPoFfx1g8U0aclrU5UBy+7gDEhqJ/gIVRrxTGQ2yMnRADspDq670uMgTontn1+7Pp6fqpMzRbN5D3Id9pMJ1+bJWQcEXqwuvsPXVKcXXuAqF91ztUZr+GAYLRjpEAqcVV7VkAJ4L/nLTbFXPzgMIZ0qhl2DiVsVvuAALPiovmHm7f+fRjRdPVrSnzEeVXbzj1d5LYftUJCRGtQ3zHlvIy4Uoxd9/kROXLuEe5Vt2ovfhKrcY9M6If2KIJIYMMSSdCfx2nPind19DUivg5D0X5WNIFvY65fbjNQkn2iu42nwsqFXVpitzN2AEDAWthZezlbj4G7YSreYhgmikZAZSuGyS0KM5MFv+tPILTB1wncBVlErTu8BRw7RFQF2waEHNxWL+/5PMflTWFPXAC7ejOu1ES3oTbf7SEbBy5QgB9QZG2LWS/TQ+7unSoxMLADLUwLTxIFti99MHrdMSM2ypaMnh6CammOabsrsQRgEOflnX7Y2d0BqGp3qOkqVGO2Iu1ITbZ7rI0y+xIVY14e447RCfOLHRIA3SwMYgHkXy3pGBLviqq3/g/ez5r+5Iiqu2JJSlNwa03Yf7WbuRO0UgZLY85ykm2tV1rcQx//gFFpWQ7tCdKkIFVUyic="
    - secure: "mDQ+2Ta0sBPUgOdaH6YlKGERdpc0W566EX08NOtBJ2SqCuwspzzvsasU/5Ck1MAOlbKo4y3VsJLbXXTG/HXmq47aDjDmfpJsejroTgzsgT7hGamXcD8KQm7ifZXasUwKxeX32+WAlK29HWIuK3ywBZ0B6T0+/yU50QXi6Q5/64Ex3Xzx1okPcCp6lRJlM0UdPvB6jsc/sln3LXJjPrLFG9WY8cBDJYK42kS2/9XYimbTaeA4HJ7+/pyBML4lKkznhvUfruZuPSj91Gc9Zg+t8oZ4IVfrrP7py1tn3CrCKyNEYB990jQ9XT5LpqU32qop1s+fCxMS/z4EVctVrmUu1CRb2QQB52mvivl1GnEx954MHbVW3UyKc/OBG/YSTQk/i6PkRIsD6u9XupdFqjHviZobHaNC2kiffAgPmSClx0TLoJ6ggMI1k4U0OT3CTQVSQPTDJ0DnB9AIwWfKZri9CbtnUjWUz6xbyxrn2HgUT5vF18fljreGrHGTkN7tioD++64p83MlIPz7uKb0xcHyBuqW0ja6BEEFGHRiLeJAJAnzf/FLYRuW/mKRWw2GXDvfFIZ5q8qzcRp6Qlbk+p8HfdVkiMZonxnRYCIZ4wBVNz88jf4R6rUkUtU4Fz4lM6Xj6jThhVZoZqqSChL8nEMVDZZOkMlrb66pTDUu1rcPgsk="
script:
  - bundle exec rake travis:script
after_success:
  - bundle exec rake travis:after_success
  - echo "$DOCKER_USERNAME"
  - echo $DOCKER_USERNAME
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME -password-stdin
  - docker build . -f production.Dockerfile -t mayurifag/mayurifag.github.io:latest
  - docker push mayurifag/mayurifag.github.io:latest
