language: ruby
rvm:
- 2.5.0
cache: bundler
branches:
  only:
  - source
script:
  - git config --global user.name 'Mayurifag'
  - git config --global user.email 'farazeus@gmail.com'
  - git remote set-url origin https://Mayurifag:${GH_TOKEN}@github.com/Mayurifag/mayurifag.github.io.git
  - bundle exec middleman build
  - bundle exec middleman deploy
