language: ruby

rvm:
- 2.6.1

cache: bundler

addons:
  apt:
    packages:
    - imagemagick

branches:
  only:
  - source

env:
  global:
    - GH_COMMIT_AUTHOR="Travis CI"
    - GH_COMMIT_EMAIL=your_email@example.com

script:
  - bundle exec rake travis:script

after_success:
  - bundle exec rake travis:after_success
