language: ruby

rvm:
  - 3.1.2
cache: bundler

addons:
  - imagemagick
services:
  - docker

branches:
  only:
    - source

env:
  global:
    - GH_COMMIT_AUTHOR='Travis CI'
    - GH_COMMIT_EMAIL='travis@travis-ci.org'
    - secure: pIqZHQgAw51hNC1zVsYfDbDzobMHu26ncPjX1KCoxaFXTZYx/AsG4NXmC2wJoIsdPoDvMwpgjFofj+/DZEg8BvCU6OZ1+qT85xp6k4FMoUb7pK4X7DkdI4GaO2oyIK6ZbAAJqcEIMfGnhp1Rc537onu2F8MMFzUKApWoOwUvo2jbrXZe62qCcFaPMVwYvvwKuHHvJd/MEIzUHqtproT5VO+VcELUzXQkg86w0ePYqVqk6hA2l8NjbOh7m02HM1yxjaBtv9I7JtocIckYNKrgjTe53RfyZPiYW90OfhRZYrp2MEm1JNhBDzkCVxOyQf3r2trXtLH9z9QyxP4Bg2cbE9DHx/TDbwFGFd7w7jEgwJ23vkNMmQRPuDW7b4Bz2kyj+u00SN4JAzPYeVTHVrqE4Xy9VM/PKZy3Gt5WgV+VK5QaCf1kN50tSAFmhoxqWsxryk/H30tIumdXcFhx3WuxeCndjgzGMWI7ZQ+FUShXvU8QmIEgIiI5KIlFs9NOPeVu9QlICJofiayTTah7dZzfueXHEkjePoF0hiG+7bVLHUT3CgZ7NoxjPTekaCKvz8gymTcmYm/lBeD4EGQAWZLgvjzAUDVhKup26gb9DHYXN7iskrxWW8/Ez36L/8lAHCqMZc4vPPFF6Xv0s9QC6zY5+ffw3x9Zr8XGtzph3KDnzIk=
    - secure: QfqNqfVjmVgKq63kL7Vzt23EbFLdWjBOr8Y3JW/RyqYd2Fm4AgvKWuRboCdhbCX5SXOiOMAciSPMHPZYU03BPhaM0mw/30+3NH69qDrg1p5hiZZA2/BQDwzZiLry8XODP599raRBF/t+PdBFZsw/U7aZWDx4ClqRX3zxWWYaYvHV8SoMxjopvunsWN5+4/yRiU4+V0ooYOO7i8dlBzGL+NTiW3G1g7tHN6/QJHBJZ5v2GRquerZK+3ZJgP0rCXBIJeVlC5d9OLt5u6HQM/ALExfRqI+MTFAMgMIXzYDQN9NDqv6zpqPPfy8zAU2c1tmluyH85T6H76InnhUUGkozx7jg47ZRhmGOZjf7F7Z5ie+O4Ug9M5YhtzS9Ir5F225zybSRBShqgpXx3Lt9Zy7D+0WTqFTB7AwFM8QXZ92AWtzWEuhKD6t7BbGDqDuG9BUdifx/LNGb5VzTAKg58DOc/Uyg2nXaZAVFl02NpDBffUG3cD50utXlAeJG7lQNeopBvx6/TkyOZQyuMZK0otxtESYGyyUGqIVQ9HpgGAa6M6E7fTAnUSOoDJm5e1lhqo69ebeWnDBJY6jd9ddgua06kMVxv3IEViFTUfJTdx2O9HOaNbKoxAKQjiUTjFgVOmIUk9ITy9CcKBj0UkWiCJpMoNt4ckvRYvcFHWSRFmAH27o=
script:
  - bundle exec rake travis:script
after_success:
  - bundle exec rake travis:after_success
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  - docker build . -f production.Dockerfile -t mayurifag/mayurifag.github.io:latest
  - docker push mayurifag/mayurifag.github.io:latest
