version: '3'
services:
  web:
    build:
      context: .
      dockerfile: development.Dockerfile
    volumes:
      - .:/mayurifag.github.io:cached
      - bundle:/bundle
    ports:
      - "4567:4567" # middleman server
      - "35729:35729" # livereload

volumes:
  bundle:
